import { Link, useParams } from "@tanstack/react-router";
import { useSuspenseQuery } from "@tanstack/react-query";
import { BadgeCheck, MapPin, Smartphone, Star } from "lucide-react";
import { Button } from "@/components/ui/button";
import { SafeImage } from "@/components/SafeImage";
import { storeOptions, storeProductsOptions } from "@/lib/queries";
import fallbackBanner from "@/assets/marketplace/store-banner.jpg.asset.json";
import fallbackProduct from "@/assets/cat-crafts.jpg";

export function PublicStorefront() {
  const { slug } = useParams({ from: "/stores/$slug" });
  const { data: store } = useSuspenseQuery(storeOptions(slug));
  const { data: products } = useSuspenseQuery(storeProductsOptions(slug));
  const location = [store.city, store.country].filter(Boolean).join(", ");
  return <div><section className="relative"><SafeImage src={store.banner_url ?? fallbackBanner.url} fallback={fallbackBanner.url} alt={`${store.name} storefront`} className="h-56 w-full object-cover sm:h-72"/><div className="absolute inset-0 bg-primary/45"/><div className="absolute inset-x-0 bottom-0"><div className="mx-auto flex max-w-7xl items-end gap-4 px-4 pb-6 sm:px-6 lg:px-8">{store.logo_url?<SafeImage src={store.logo_url} alt={`${store.name} logo`} className="h-20 w-20 shrink-0 rounded-md border-4 border-card bg-card object-cover"/>:null}<div className="min-w-0 text-primary-foreground"><h1 className="flex items-center gap-2 font-heading text-3xl font-bold sm:text-4xl"><span className="truncate">{store.business_name || store.name}</span>{store.is_verified?<BadgeCheck className="h-6 w-6 shrink-0 text-accent"/>:null}</h1>{location?<p className="mt-1 flex items-center gap-1.5 text-sm"><MapPin className="h-4 w-4"/>{location}</p>:null}</div></div></div></section><section className="mx-auto grid max-w-7xl gap-10 px-4 py-12 sm:px-6 lg:grid-cols-[minmax(0,.65fr)_minmax(0,1.35fr)] lg:px-8"><div><p className="text-xs font-bold uppercase text-brand-gold">About the business</p><p className="mt-3 leading-7 text-muted-foreground">{store.description || "This business has not added its full story yet."}</p><div className="mt-5 flex flex-wrap gap-4 text-sm">{store.rating?<span className="flex items-center gap-1.5"><Star className="h-4 w-4 text-accent"/>{Number(store.rating).toFixed(1)} rating</span>:null}<span className="font-semibold">{store.is_verified?"Verified by Afromart":"Verification pending"}</span></div><Button asChild className="mt-7"><Link to="/download"><Smartphone className="h-4 w-4"/>View on the Afromart App</Link></Button></div><div><h2 className="font-heading text-2xl font-bold">What this business offers</h2>{products.length?<div className="mt-5 grid gap-4 sm:grid-cols-2">{products.slice(0,6).map(product=><article key={product.id} className="grid grid-cols-[6rem_minmax(0,1fr)] gap-4 rounded-md border bg-card p-3"><SafeImage src={product.product_images?.[0]?.url} fallback={fallbackProduct} alt={product.name} className="aspect-square w-full rounded-md object-cover"/><div className="min-w-0"><h3 className="font-heading font-bold">{product.name}</h3><p className="mt-1 line-clamp-3 text-sm text-muted-foreground">{product.description || "Available through this business on Afromart."}</p></div></article>)}</div>:<p className="mt-4 text-muted-foreground">This business is preparing its public catalogue.</p>}</div></section></div>;
}