import { Link } from "@tanstack/react-router";
import { ArrowRight, BadgeCheck, Building2, Globe2, Handshake, Languages, MessageCircle, ShieldCheck, Smartphone, Store, Wrench } from "lucide-react";
import { Button } from "@/components/ui/button";
import { StoreBadges } from "@/components/StoreBadges";
import communityImage from "@/assets/onboarding/afromart-community.png.asset.json";
import businessImage from "@/assets/marketplace/store-banner.jpg.asset.json";
import tailoringImage from "@/assets/marketplace/svc-tailoring.jpg.asset.json";
import logisticsImage from "@/assets/marketplace/svc-dispatch.jpg.asset.json";
import repairsImage from "@/assets/marketplace/svc-repair.jpg.asset.json";
import homeScreen from "@/assets/app-screens/home.png.asset.json";
import categoriesScreen from "@/assets/app-screens/categories.png.asset.json";
import servicesScreen from "@/assets/app-screens/services-home.png.asset.json";

function Intro({ eyebrow, title, body }: { eyebrow: string; title: string; body: string }) {
  return <section className="brand-soft border-b"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-20"><p className="text-xs font-bold uppercase text-brand-gold">{eyebrow}</p><h1 className="mt-3 max-w-4xl font-heading text-4xl font-bold text-primary sm:text-6xl">{title}</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-muted-foreground">{body}</p></div></section>;
}

export function AboutPage() {
  return <><Intro eyebrow="About Afromart" title="One digital marketplace for African commerce." body="Afromart connects buyers, sellers, service providers and local businesses across Africa through discovery, communication and a trusted mobile marketplace experience." /><section className="mx-auto grid max-w-7xl items-center gap-10 px-4 py-16 sm:px-6 lg:grid-cols-2 lg:px-8 lg:py-20"><img src={communityImage.url} alt="African entrepreneurs building commerce together" className="aspect-[1.25/1] w-full rounded-lg object-cover" /><div><h2 className="font-heading text-3xl font-bold">Built around African markets</h2><p className="mt-4 leading-7 text-muted-foreground">The platform brings products, services, direct communication, business identity and cross-border opportunity into one localized ecosystem. The public website explains that ecosystem; the mobile app delivers its complete marketplace experience.</p><div className="mt-7 grid gap-4 sm:grid-cols-2">{[{icon:Globe2,title:"Pan-African reach"},{icon:Languages,title:"Ten launch languages"},{icon:MessageCircle,title:"Direct communication"},{icon:ShieldCheck,title:"Trust and support"}].map((item)=><div key={item.title} className="flex items-center gap-3 border-t p-3"><item.icon className="h-5 w-5 text-primary" /><span className="font-semibold">{item.title}</span></div>)}</div><Button asChild className="mt-7"><Link to="/download">Get the Afromart App</Link></Button></div></section></>;
}

export function ServicesInfoPage() {
  const items=[{title:"Tailoring",body:"Bespoke clothing, alterations and textile services.",image:tailoringImage.url},{title:"Logistics",body:"Local dispatch and regional delivery support.",image:logisticsImage.url},{title:"Repairs",body:"Trusted help for devices and household equipment.",image:repairsImage.url},{title:"Freelance services",body:"Creative, digital and professional expertise.",image:businessImage.url}];
  return <><Intro eyebrow="Services on Afromart" title="Find skilled people and practical services." body="Discover service providers by category and location, review their business profile, then continue in the Afromart app to connect, discuss and request the work." /><section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{items.map(item=><article key={item.title} className="overflow-hidden rounded-md border bg-card"><img src={item.image} alt={`${item.title} in Africa`} className="aspect-[1.35/1] w-full object-cover"/><div className="p-5"><h2 className="font-heading text-xl font-bold">{item.title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{item.body}</p></div></article>)}</div><div className="mt-12 bg-primary p-7 text-primary-foreground sm:p-10"><h2 className="font-heading text-3xl font-bold">Explore services in the app</h2><p className="mt-3 max-w-2xl text-primary-foreground/75">Search by location, review provider profiles and continue the conversation from your phone.</p><Button asChild variant="secondary" className="mt-6"><Link to="/download">Download Afromart <ArrowRight className="h-4 w-4" /></Link></Button></div></section></>;
}

export function BusinessPage() {
  return <><Intro eyebrow="For businesses" title="Build your Afromart business presence." body="Create a seller or service-provider profile, present your business clearly, verify your identity and manage the listings that appear in the mobile marketplace." /><section className="mx-auto grid max-w-7xl items-center gap-10 px-4 py-16 sm:px-6 lg:grid-cols-2 lg:px-8"><img src={businessImage.url} alt="African business owner managing her storefront" className="aspect-[1.2/1] w-full rounded-lg object-cover"/><div><h2 className="font-heading text-3xl font-bold">Your public business profile</h2><ul className="mt-6 space-y-4">{["Business name, description, logo and banner","Location and practical business information","Products and services managed from one workspace","Verification documents reviewed privately","A public profile visitors can view before opening the app"].map(text=><li key={text} className="flex gap-3"><BadgeCheck className="mt-0.5 h-5 w-5 shrink-0 text-primary"/><span>{text}</span></li>)}</ul><div className="mt-8 flex flex-wrap gap-3"><Button asChild><Link to="/sell/start">Create Your Business Profile</Link></Button><Button asChild variant="outline"><Link to="/auth" search={{redirect:"/seller"}}>Business Login</Link></Button></div></div></section></>;
}

export function HowItWorksPage() {
  const steps=[{icon:Globe2,title:"Discover",body:"Learn about businesses, products and services available across African markets."},{icon:MessageCircle,title:"Connect",body:"Find the right seller or provider and understand their public business profile."},{icon:Smartphone,title:"Continue in the app",body:"Use the Afromart mobile app for marketplace interaction and transactions."},{icon:Building2,title:"Grow",body:"Businesses manage their presence, listings and verification through their account."}];
  return <><Intro eyebrow="How Afromart works" title="From local discovery to continental opportunity." body="Afromart keeps discovery simple for users and gives African businesses a professional path to reach customers."/><section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{steps.map((step,index)=><article key={step.title} className="border-t-2 border-accent bg-card p-6 shadow-sm"><span className="text-xs font-bold text-brand-gold">0{index+1}</span><step.icon className="mt-5 h-7 w-7 text-primary"/><h2 className="mt-4 font-heading text-xl font-bold">{step.title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{step.body}</p></article>)}</div><div className="mt-12 flex justify-center"><Button asChild size="lg"><Link to="/download">Download the App</Link></Button></div></section></>;
}

export function DownloadPage() {
  return <section className="min-h-[calc(100vh-5rem)] bg-primary text-primary-foreground"><div className="mx-auto grid max-w-7xl items-center gap-12 px-4 py-16 sm:px-6 lg:grid-cols-[minmax(0,.85fr)_minmax(30rem,1.15fr)] lg:px-8 lg:py-20"><div><p className="text-xs font-bold uppercase text-accent">The full Afromart experience</p><h1 className="mt-3 font-heading text-4xl font-bold sm:text-6xl">Africa's marketplace, on your phone.</h1><p className="mt-5 max-w-xl text-lg leading-8 text-primary-foreground/75">Discover products and services, connect with businesses and use the complete marketplace experience in the Afromart mobile app.</p><StoreBadges className="mt-8"/><p className="mt-5 text-xs text-primary-foreground/60">Official store links will be added when the mobile apps are released.</p></div><div className="grid grid-cols-3 items-end gap-3 sm:gap-5"><img src={categoriesScreen.url} alt="Afromart categories screen" className="w-full rounded-lg shadow-xl"/><img src={homeScreen.url} alt="Afromart home screen" className="w-full rounded-lg shadow-xl"/><img src={servicesScreen.url} alt="Afromart services screen" className="w-full rounded-lg shadow-xl"/></div></div></section>;
}