/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as GuestRouteImport } from './routes/guest'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SellRouteImport } from './routes/sell'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SupportRouteImport } from './routes/support'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedSellerRouteImport } from './routes/_authenticated/seller'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSupportChatRouteImport } from './routes/_authenticated/support-chat'
import { Route as ApiSupportChatRouteImport } from './routes/api/support-chat'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as SellIndexRouteImport } from './routes/sell.index'
import { Route as SellStartRouteImport } from './routes/sell.start'
import { Route as StoresSlugRouteImport } from './routes/stores.$slug'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated/messages.index'
import { Route as AuthenticatedMessagesConversationIdRouteImport } from './routes/_authenticated/messages.$conversationId'
import { Route as AuthenticatedOrdersOrderIdRouteImport } from './routes/_authenticated/orders.$orderId'
import { Route as AuthenticatedSupportChatIndexRouteImport } from './routes/_authenticated/support-chat.index'
import { Route as AuthenticatedSupportChatThreadIdRouteImport } from './routes/_authenticated/support-chat.$threadId'
import { Route as ApiPublicMediaObjectRouteImport } from './routes/api/public/media.$object'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks/stripe'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/guest',
  path: '/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSellerRoute = AuthenticatedSellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportChatRoute =
  AuthenticatedSupportChatRouteImport.update({
    id: '/support-chat',
    path: '/support-chat',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiSupportChatRoute = ApiSupportChatRouteImport.update({
  id: '/api/support-chat',
  path: '/api/support-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRoute,
} as any)
const SellIndexRoute = SellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SellRoute,
} as any)
const SellStartRoute = SellStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => SellRoute,
} as any)
const StoresSlugRoute = StoresSlugRouteImport.update({
  id: '/stores/$slug',
  path: '/stores/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMessagesRoute,
  } as any)
const AuthenticatedMessagesConversationIdRoute =
  AuthenticatedMessagesConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthenticatedMessagesRoute,
  } as any)
const AuthenticatedOrdersOrderIdRoute =
  AuthenticatedOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupportChatIndexRoute =
  AuthenticatedSupportChatIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSupportChatRoute,
  } as any)
const AuthenticatedSupportChatThreadIdRoute =
  AuthenticatedSupportChatThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedSupportChatRoute,
  } as any)
const ApiPublicMediaObjectRoute = ApiPublicMediaObjectRouteImport.update({
  id: '/api/public/media/$object',
  path: '/api/public/media/$object',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({
  id: '/api/public/webhooks/stripe',
  path: '/api/public/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/business': typeof BusinessRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/coming-soon': typeof ComingSoonRoute
  '/download': typeof DownloadRoute
  '/guest': typeof GuestRoute
  '/home': typeof HomeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/onboarding': typeof OnboardingRoute
  '/products': typeof ProductsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sell': typeof SellRouteWithChildren
  '/services': typeof ServicesRoute
  '/support': typeof SupportRoute
  '/account': typeof AuthenticatedAccountRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/seller': typeof AuthenticatedSellerRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support-chat': typeof AuthenticatedSupportChatRouteWithChildren
  '/api/support-chat': typeof ApiSupportChatRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/sell/start': typeof SellStartRoute
  '/stores/$slug': typeof StoresSlugRoute
  '/products/': typeof ProductsIndexRoute
  '/sell/': typeof SellIndexRoute
  '/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/support-chat/$threadId': typeof AuthenticatedSupportChatThreadIdRoute
  '/messages/': typeof AuthenticatedMessagesIndexRoute
  '/support-chat/': typeof AuthenticatedSupportChatIndexRoute
  '/api/public/media/$object': typeof ApiPublicMediaObjectRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/business': typeof BusinessRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/coming-soon': typeof ComingSoonRoute
  '/download': typeof DownloadRoute
  '/guest': typeof GuestRoute
  '/home': typeof HomeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/support': typeof SupportRoute
  '/account': typeof AuthenticatedAccountRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/seller': typeof AuthenticatedSellerRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/support-chat': typeof ApiSupportChatRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/sell/start': typeof SellStartRoute
  '/stores/$slug': typeof StoresSlugRoute
  '/products': typeof ProductsIndexRoute
  '/sell': typeof SellIndexRoute
  '/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/support-chat/$threadId': typeof AuthenticatedSupportChatThreadIdRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/support-chat': typeof AuthenticatedSupportChatIndexRoute
  '/api/public/media/$object': typeof ApiPublicMediaObjectRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/business': typeof BusinessRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/coming-soon': typeof ComingSoonRoute
  '/download': typeof DownloadRoute
  '/guest': typeof GuestRoute
  '/home': typeof HomeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/onboarding': typeof OnboardingRoute
  '/products': typeof ProductsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sell': typeof SellRouteWithChildren
  '/services': typeof ServicesRoute
  '/support': typeof SupportRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/seller': typeof AuthenticatedSellerRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/support-chat': typeof AuthenticatedSupportChatRouteWithChildren
  '/api/support-chat': typeof ApiSupportChatRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/sell/start': typeof SellStartRoute
  '/stores/$slug': typeof StoresSlugRoute
  '/products/': typeof ProductsIndexRoute
  '/sell/': typeof SellIndexRoute
  '/_authenticated/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/_authenticated/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/_authenticated/support-chat/$threadId': typeof AuthenticatedSupportChatThreadIdRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
  '/_authenticated/support-chat/': typeof AuthenticatedSupportChatIndexRoute
  '/api/public/media/$object': typeof ApiPublicMediaObjectRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/business'
    | '/cart'
    | '/categories'
    | '/coming-soon'
    | '/download'
    | '/guest'
    | '/home'
    | '/how-it-works'
    | '/onboarding'
    | '/products'
    | '/reset-password'
    | '/sell'
    | '/services'
    | '/support'
    | '/account'
    | '/checkout'
    | '/messages'
    | '/notifications'
    | '/seller'
    | '/settings'
    | '/support-chat'
    | '/api/support-chat'
    | '/products/$slug'
    | '/sell/start'
    | '/stores/$slug'
    | '/products/'
    | '/sell/'
    | '/messages/$conversationId'
    | '/orders/$orderId'
    | '/support-chat/$threadId'
    | '/messages/'
    | '/support-chat/'
    | '/api/public/media/$object'
    | '/api/public/webhooks/stripe'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/business'
    | '/cart'
    | '/categories'
    | '/coming-soon'
    | '/download'
    | '/guest'
    | '/home'
    | '/how-it-works'
    | '/onboarding'
    | '/reset-password'
    | '/services'
    | '/support'
    | '/account'
    | '/checkout'
    | '/notifications'
    | '/seller'
    | '/settings'
    | '/api/support-chat'
    | '/products/$slug'
    | '/sell/start'
    | '/stores/$slug'
    | '/products'
    | '/sell'
    | '/messages/$conversationId'
    | '/orders/$orderId'
    | '/support-chat/$threadId'
    | '/messages'
    | '/support-chat'
    | '/api/public/media/$object'
    | '/api/public/webhooks/stripe'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/business'
    | '/cart'
    | '/categories'
    | '/coming-soon'
    | '/download'
    | '/guest'
    | '/home'
    | '/how-it-works'
    | '/onboarding'
    | '/products'
    | '/reset-password'
    | '/sell'
    | '/services'
    | '/support'
    | '/_authenticated/account'
    | '/_authenticated/checkout'
    | '/_authenticated/messages'
    | '/_authenticated/notifications'
    | '/_authenticated/seller'
    | '/_authenticated/settings'
    | '/_authenticated/support-chat'
    | '/api/support-chat'
    | '/products/$slug'
    | '/sell/start'
    | '/stores/$slug'
    | '/products/'
    | '/sell/'
    | '/_authenticated/messages/$conversationId'
    | '/_authenticated/orders/$orderId'
    | '/_authenticated/support-chat/$threadId'
    | '/_authenticated/messages/'
    | '/_authenticated/support-chat/'
    | '/api/public/media/$object'
    | '/api/public/webhooks/stripe'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BusinessRoute: typeof BusinessRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  ComingSoonRoute: typeof ComingSoonRoute
  DownloadRoute: typeof DownloadRoute
  GuestRoute: typeof GuestRoute
  HomeRoute: typeof HomeRoute
  HowItWorksRoute: typeof HowItWorksRoute
  OnboardingRoute: typeof OnboardingRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SellRoute: typeof SellRouteWithChildren
  ServicesRoute: typeof ServicesRoute
  SupportRoute: typeof SupportRoute
  ApiSupportChatRoute: typeof ApiSupportChatRoute
  StoresSlugRoute: typeof StoresSlugRoute
  ApiPublicMediaObjectRoute: typeof ApiPublicMediaObjectRoute
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest': {
      id: '/guest'
      path: '/guest'
      fullPath: '/guest'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seller': {
      id: '/_authenticated/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof AuthenticatedSellerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support-chat': {
      id: '/_authenticated/support-chat'
      path: '/support-chat'
      fullPath: '/support-chat'
      preLoaderRoute: typeof AuthenticatedSupportChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/support-chat': {
      id: '/api/support-chat'
      path: '/api/support-chat'
      fullPath: '/api/support-chat'
      preLoaderRoute: typeof ApiSupportChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/sell/': {
      id: '/sell/'
      path: '/'
      fullPath: '/sell/'
      preLoaderRoute: typeof SellIndexRouteImport
      parentRoute: typeof SellRoute
    }
    '/sell/start': {
      id: '/sell/start'
      path: '/start'
      fullPath: '/sell/start'
      preLoaderRoute: typeof SellStartRouteImport
      parentRoute: typeof SellRoute
    }
    '/stores/$slug': {
      id: '/stores/$slug'
      path: '/stores/$slug'
      fullPath: '/stores/$slug'
      preLoaderRoute: typeof StoresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedMessagesRoute
    }
    '/_authenticated/messages/$conversationId': {
      id: '/_authenticated/messages/$conversationId'
      path: '/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof AuthenticatedMessagesConversationIdRouteImport
      parentRoute: typeof AuthenticatedMessagesRoute
    }
    '/_authenticated/orders/$orderId': {
      id: '/_authenticated/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support-chat/': {
      id: '/_authenticated/support-chat/'
      path: '/'
      fullPath: '/support-chat/'
      preLoaderRoute: typeof AuthenticatedSupportChatIndexRouteImport
      parentRoute: typeof AuthenticatedSupportChatRoute
    }
    '/_authenticated/support-chat/$threadId': {
      id: '/_authenticated/support-chat/$threadId'
      path: '/$threadId'
      fullPath: '/support-chat/$threadId'
      preLoaderRoute: typeof AuthenticatedSupportChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedSupportChatRoute
    }
    '/api/public/media/$object': {
      id: '/api/public/media/$object'
      path: '/api/public/media/$object'
      fullPath: '/api/public/media/$object'
      preLoaderRoute: typeof ApiPublicMediaObjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/stripe': {
      id: '/api/public/webhooks/stripe'
      path: '/api/public/webhooks/stripe'
      fullPath: '/api/public/webhooks/stripe'
      preLoaderRoute: typeof ApiPublicWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedMessagesRouteChildren {
  AuthenticatedMessagesConversationIdRoute: typeof AuthenticatedMessagesConversationIdRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
}

const AuthenticatedMessagesRouteChildren: AuthenticatedMessagesRouteChildren = {
  AuthenticatedMessagesConversationIdRoute:
    AuthenticatedMessagesConversationIdRoute,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
}

const AuthenticatedMessagesRouteWithChildren =
  AuthenticatedMessagesRoute._addFileChildren(
    AuthenticatedMessagesRouteChildren,
  )

interface AuthenticatedSupportChatRouteChildren {
  AuthenticatedSupportChatThreadIdRoute: typeof AuthenticatedSupportChatThreadIdRoute
  AuthenticatedSupportChatIndexRoute: typeof AuthenticatedSupportChatIndexRoute
}

const AuthenticatedSupportChatRouteChildren: AuthenticatedSupportChatRouteChildren =
  {
    AuthenticatedSupportChatThreadIdRoute:
      AuthenticatedSupportChatThreadIdRoute,
    AuthenticatedSupportChatIndexRoute: AuthenticatedSupportChatIndexRoute,
  }

const AuthenticatedSupportChatRouteWithChildren =
  AuthenticatedSupportChatRoute._addFileChildren(
    AuthenticatedSupportChatRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRouteWithChildren
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedSellerRoute: typeof AuthenticatedSellerRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSupportChatRoute: typeof AuthenticatedSupportChatRouteWithChildren
  AuthenticatedOrdersOrderIdRoute: typeof AuthenticatedOrdersOrderIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRouteWithChildren,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedSellerRoute: AuthenticatedSellerRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSupportChatRoute: AuthenticatedSupportChatRouteWithChildren,
  AuthenticatedOrdersOrderIdRoute: AuthenticatedOrdersOrderIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ProductsRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsSlugRoute: ProductsSlugRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface SellRouteChildren {
  SellStartRoute: typeof SellStartRoute
  SellIndexRoute: typeof SellIndexRoute
}

const SellRouteChildren: SellRouteChildren = {
  SellStartRoute: SellStartRoute,
  SellIndexRoute: SellIndexRoute,
}

const SellRouteWithChildren = SellRoute._addFileChildren(SellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BusinessRoute: BusinessRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  ComingSoonRoute: ComingSoonRoute,
  DownloadRoute: DownloadRoute,
  GuestRoute: GuestRoute,
  HomeRoute: HomeRoute,
  HowItWorksRoute: HowItWorksRoute,
  OnboardingRoute: OnboardingRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SellRoute: SellRouteWithChildren,
  ServicesRoute: ServicesRoute,
  SupportRoute: SupportRoute,
  ApiSupportChatRoute: ApiSupportChatRoute,
  StoresSlugRoute: StoresSlugRoute,
  ApiPublicMediaObjectRoute: ApiPublicMediaObjectRoute,
  ApiPublicWebhooksStripeRoute: ApiPublicWebhooksStripeRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
